# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deliver_form.ui'
#
# Created: Sun May 22 16:43:59 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_deliver_form(object):
    def setupUi(self, deliver_form):
        deliver_form.setObjectName(_fromUtf8("deliver_form"))
        deliver_form.resize(1265, 401)
        self.gridLayout_2 = QtGui.QGridLayout(deliver_form)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.bill_number_date = QtGui.QLabel(deliver_form)
        self.bill_number_date.setObjectName(_fromUtf8("bill_number_date"))
        self.gridLayout.addWidget(self.bill_number_date, 0, 0, 1, 3)
        self.label = QtGui.QLabel(deliver_form)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.save_close_btn = QtGui.QPushButton(deliver_form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.save_close_btn.sizePolicy().hasHeightForWidth())
        self.save_close_btn.setSizePolicy(sizePolicy)
        self.save_close_btn.setMinimumSize(QtCore.QSize(200, 0))
        self.save_close_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.save_close_btn.setObjectName(_fromUtf8("save_close_btn"))
        self.gridLayout.addWidget(self.save_close_btn, 4, 0, 1, 2)
        self.save_btn = QtGui.QPushButton(deliver_form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.save_btn.sizePolicy().hasHeightForWidth())
        self.save_btn.setSizePolicy(sizePolicy)
        self.save_btn.setMinimumSize(QtCore.QSize(200, 0))
        self.save_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.save_btn.setObjectName(_fromUtf8("save_btn"))
        self.gridLayout.addWidget(self.save_btn, 4, 2, 1, 2)
        self.label_3 = QtGui.QLabel(deliver_form)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 4, 8, 1, 1)
        self.label_2 = QtGui.QLabel(deliver_form)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 3, 1, 1)
        self.deliver_date = QtGui.QLineEdit(deliver_form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.deliver_date.sizePolicy().hasHeightForWidth())
        self.deliver_date.setSizePolicy(sizePolicy)
        self.deliver_date.setMinimumSize(QtCore.QSize(100, 0))
        self.deliver_date.setMaximumSize(QtCore.QSize(270, 16777215))
        self.deliver_date.setObjectName(_fromUtf8("deliver_date"))
        self.gridLayout.addWidget(self.deliver_date, 1, 4, 1, 1)
        self.close_btn = QtGui.QPushButton(deliver_form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.close_btn.sizePolicy().hasHeightForWidth())
        self.close_btn.setSizePolicy(sizePolicy)
        self.close_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.close_btn.setMaximumSize(QtCore.QSize(200, 500))
        self.close_btn.setObjectName(_fromUtf8("close_btn"))
        self.gridLayout.addWidget(self.close_btn, 4, 7, 1, 1)
        self.tableWidget = QtGui.QTableWidget(deliver_form)
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 3, 0, 1, 9)
        self.distributor_combo = QtGui.QComboBox(deliver_form)
        self.distributor_combo.setObjectName(_fromUtf8("distributor_combo"))
        self.gridLayout.addWidget(self.distributor_combo, 1, 1, 1, 2)
        self.print_cards_btn = QtGui.QPushButton(deliver_form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.print_cards_btn.sizePolicy().hasHeightForWidth())
        self.print_cards_btn.setSizePolicy(sizePolicy)
        self.print_cards_btn.setMinimumSize(QtCore.QSize(200, 0))
        self.print_cards_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.print_cards_btn.setObjectName(_fromUtf8("print_cards_btn"))
        self.gridLayout.addWidget(self.print_cards_btn, 4, 4, 1, 1)
        self.print_bill_btn = QtGui.QPushButton(deliver_form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(200)
        sizePolicy.setVerticalStretch(20)
        sizePolicy.setHeightForWidth(self.print_bill_btn.sizePolicy().hasHeightForWidth())
        self.print_bill_btn.setSizePolicy(sizePolicy)
        self.print_bill_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.print_bill_btn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.print_bill_btn.setObjectName(_fromUtf8("print_bill_btn"))
        self.gridLayout.addWidget(self.print_bill_btn, 4, 5, 1, 1)
        self.label_4 = QtGui.QLabel(deliver_form)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 5, 1, 1)
        self.financing_combo = QtGui.QComboBox(deliver_form)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.financing_combo.sizePolicy().hasHeightForWidth())
        self.financing_combo.setSizePolicy(sizePolicy)
        self.financing_combo.setMinimumSize(QtCore.QSize(200, 0))
        self.financing_combo.setObjectName(_fromUtf8("financing_combo"))
        self.financing_combo.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.financing_combo, 1, 6, 1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(deliver_form)
        self.financing_combo.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(deliver_form)

    def retranslateUi(self, deliver_form):
        deliver_form.setWindowTitle(QtGui.QApplication.translate("deliver_form", "Приходная накладная", None, QtGui.QApplication.UnicodeUTF8))
        self.bill_number_date.setText(QtGui.QApplication.translate("deliver_form", "Накладная №1 от 10.10.10", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("deliver_form", "Поставщик", None, QtGui.QApplication.UnicodeUTF8))
        self.save_close_btn.setText(QtGui.QApplication.translate("deliver_form", "Провести накладную", None, QtGui.QApplication.UnicodeUTF8))
        self.save_btn.setText(QtGui.QApplication.translate("deliver_form", "Сохранить и не проводить", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("deliver_form", "Всего лс на сумму 0.00р", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("deliver_form", "Дата поступления", None, QtGui.QApplication.UnicodeUTF8))
        self.deliver_date.setInputMask(QtGui.QApplication.translate("deliver_form", "00.00.0000; ", None, QtGui.QApplication.UnicodeUTF8))
        self.close_btn.setText(QtGui.QApplication.translate("deliver_form", "Закрыть без сохранения", None, QtGui.QApplication.UnicodeUTF8))
        self.print_cards_btn.setText(QtGui.QApplication.translate("deliver_form", "Печать стел. карт", None, QtGui.QApplication.UnicodeUTF8))
        self.print_bill_btn.setText(QtGui.QApplication.translate("deliver_form", "Печать накладной", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("deliver_form", "Источник финансирования", None, QtGui.QApplication.UnicodeUTF8))
        self.financing_combo.setItemText(0, QtGui.QApplication.translate("deliver_form", "Источник финансирования", None, QtGui.QApplication.UnicodeUTF8))

