# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created: Sun May 22 18:33:41 2011
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(767, 477)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.mdiArea = QtGui.QMdiArea(self.centralwidget)
        self.mdiArea.setObjectName(_fromUtf8("mdiArea"))
        self.gridLayout.addWidget(self.mdiArea, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 767, 25))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menu = QtGui.QMenu(self.menubar)
        self.menu.setObjectName(_fromUtf8("menu"))
        self.menu_2 = QtGui.QMenu(self.menubar)
        self.menu_2.setObjectName(_fromUtf8("menu_2"))
        self.menu_5 = QtGui.QMenu(self.menu_2)
        self.menu_5.setObjectName(_fromUtf8("menu_5"))
        self.menu_4 = QtGui.QMenu(self.menu_2)
        self.menu_4.setObjectName(_fromUtf8("menu_4"))
        self.menu_3 = QtGui.QMenu(self.menubar)
        self.menu_3.setObjectName(_fromUtf8("menu_3"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.deliver_action = QtGui.QAction(MainWindow)
        self.deliver_action.setObjectName(_fromUtf8("deliver_action"))
        self.menu_exit = QtGui.QAction(MainWindow)
        self.menu_exit.setObjectName(_fromUtf8("menu_exit"))
        self.sale_action = QtGui.QAction(MainWindow)
        self.sale_action.setObjectName(_fromUtf8("sale_action"))
        self.all_distributors_action = QtGui.QAction(MainWindow)
        self.all_distributors_action.setObjectName(_fromUtf8("all_distributors_action"))
        self.all_manufacters_action = QtGui.QAction(MainWindow)
        self.all_manufacters_action.setObjectName(_fromUtf8("all_manufacters_action"))
        self.all_delivers_action = QtGui.QAction(MainWindow)
        self.all_delivers_action.setObjectName(_fromUtf8("all_delivers_action"))
        self.all_sales_action = QtGui.QAction(MainWindow)
        self.all_sales_action.setObjectName(_fromUtf8("all_sales_action"))
        self.all_recipes_action = QtGui.QAction(MainWindow)
        self.all_recipes_action.setObjectName(_fromUtf8("all_recipes_action"))
        self.all_medorg_action = QtGui.QAction(MainWindow)
        self.all_medorg_action.setObjectName(_fromUtf8("all_medorg_action"))
        self.all_patients_action = QtGui.QAction(MainWindow)
        self.all_patients_action.setObjectName(_fromUtf8("all_patients_action"))
        self.all_ills_action = QtGui.QAction(MainWindow)
        self.all_ills_action.setObjectName(_fromUtf8("all_ills_action"))
        self.action_12 = QtGui.QAction(MainWindow)
        self.action_12.setObjectName(_fromUtf8("action_12"))
        self.action_14 = QtGui.QAction(MainWindow)
        self.action_14.setObjectName(_fromUtf8("action_14"))
        self.all_drugs_action = QtGui.QAction(MainWindow)
        self.all_drugs_action.setObjectName(_fromUtf8("all_drugs_action"))
        self.all_doctors_action = QtGui.QAction(MainWindow)
        self.all_doctors_action.setObjectName(_fromUtf8("all_doctors_action"))
        self.menu.addAction(self.deliver_action)
        self.menu.addAction(self.sale_action)
        self.menu.addSeparator()
        self.menu.addAction(self.menu_exit)
        self.menu_5.addAction(self.action_12)
        self.menu_5.addAction(self.action_14)
        self.menu_5.addAction(self.all_drugs_action)
        self.menu_4.addAction(self.all_manufacters_action)
        self.menu_4.addAction(self.all_medorg_action)
        self.menu_4.addAction(self.all_patients_action)
        self.menu_4.addAction(self.all_distributors_action)
        self.menu_4.addAction(self.all_doctors_action)
        self.menu_2.addAction(self.menu_5.menuAction())
        self.menu_2.addAction(self.all_recipes_action)
        self.menu_2.addAction(self.all_ills_action)
        self.menu_2.addAction(self.menu_4.menuAction())
        self.menu_3.addAction(self.all_delivers_action)
        self.menu_3.addAction(self.all_sales_action)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.menu_exit, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.menu.setTitle(QtGui.QApplication.translate("MainWindow", "Файл", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_2.setTitle(QtGui.QApplication.translate("MainWindow", "Справочники", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_5.setTitle(QtGui.QApplication.translate("MainWindow", "Лекарственные средства", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_4.setTitle(QtGui.QApplication.translate("MainWindow", "Люди", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_3.setTitle(QtGui.QApplication.translate("MainWindow", "Накладные", None, QtGui.QApplication.UnicodeUTF8))
        self.deliver_action.setText(QtGui.QApplication.translate("MainWindow", "Приход лс", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_exit.setText(QtGui.QApplication.translate("MainWindow", "Выход", None, QtGui.QApplication.UnicodeUTF8))
        self.sale_action.setText(QtGui.QApplication.translate("MainWindow", "Отпуск лс", None, QtGui.QApplication.UnicodeUTF8))
        self.all_distributors_action.setText(QtGui.QApplication.translate("MainWindow", "Поставщики", None, QtGui.QApplication.UnicodeUTF8))
        self.all_manufacters_action.setText(QtGui.QApplication.translate("MainWindow", "Производители", None, QtGui.QApplication.UnicodeUTF8))
        self.all_delivers_action.setText(QtGui.QApplication.translate("MainWindow", "Приходные", None, QtGui.QApplication.UnicodeUTF8))
        self.all_sales_action.setText(QtGui.QApplication.translate("MainWindow", "Отпускные", None, QtGui.QApplication.UnicodeUTF8))
        self.all_recipes_action.setText(QtGui.QApplication.translate("MainWindow", "Рецепты", None, QtGui.QApplication.UnicodeUTF8))
        self.all_medorg_action.setText(QtGui.QApplication.translate("MainWindow", "Медицинские организации", None, QtGui.QApplication.UnicodeUTF8))
        self.all_patients_action.setText(QtGui.QApplication.translate("MainWindow", "Пациенты", None, QtGui.QApplication.UnicodeUTF8))
        self.all_ills_action.setText(QtGui.QApplication.translate("MainWindow", "Заболевания", None, QtGui.QApplication.UnicodeUTF8))
        self.action_12.setText(QtGui.QApplication.translate("MainWindow", "Предельные оптовые цены", None, QtGui.QApplication.UnicodeUTF8))
        self.action_14.setText(QtGui.QApplication.translate("MainWindow", "Забракованные препараты", None, QtGui.QApplication.UnicodeUTF8))
        self.all_drugs_action.setText(QtGui.QApplication.translate("MainWindow", "Склад", None, QtGui.QApplication.UnicodeUTF8))
        self.all_doctors_action.setText(QtGui.QApplication.translate("MainWindow", "Врачи", None, QtGui.QApplication.UnicodeUTF8))

